// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaQW8B1FhIJYa3G8Pqjd1zJbUa5xI4cFs',
    appId: '1:944968193026:web:ca3e091f1fd2ee1f7b831b',
    messagingSenderId: '944968193026',
    projectId: 'project-points-30449',
    authDomain: 'project-points-30449.firebaseapp.com',
    storageBucket: 'project-points-30449.appspot.com',
    measurementId: 'G-0M7PG3LYNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp6TELA5_QZuPYI-Ln5v03iy8Lvr16LDk',
    appId: '1:944968193026:android:a614498e3dafba487b831b',
    messagingSenderId: '944968193026',
    projectId: 'project-points-30449',
    storageBucket: 'project-points-30449.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2rM0OiBm-v5ut2ryl9rGJvNPpHRa6KHI',
    appId: '1:944968193026:ios:7260fe51bd991d1d7b831b',
    messagingSenderId: '944968193026',
    projectId: 'project-points-30449',
    storageBucket: 'project-points-30449.appspot.com',
    androidClientId: '944968193026-5lmudta4kshpkujcjj6oocc22mc8lke8.apps.googleusercontent.com',
    iosClientId: '944968193026-fmvv4jvur5m8mctb9h7scvgcgit8dij8.apps.googleusercontent.com',
    iosBundleId: 'com.example.points',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2rM0OiBm-v5ut2ryl9rGJvNPpHRa6KHI',
    appId: '1:944968193026:ios:7260fe51bd991d1d7b831b',
    messagingSenderId: '944968193026',
    projectId: 'project-points-30449',
    storageBucket: 'project-points-30449.appspot.com',
    androidClientId: '944968193026-5lmudta4kshpkujcjj6oocc22mc8lke8.apps.googleusercontent.com',
    iosClientId: '944968193026-fmvv4jvur5m8mctb9h7scvgcgit8dij8.apps.googleusercontent.com',
    iosBundleId: 'com.example.points',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaQW8B1FhIJYa3G8Pqjd1zJbUa5xI4cFs',
    appId: '1:944968193026:web:e4a38fdedc4a14fe7b831b',
    messagingSenderId: '944968193026',
    projectId: 'project-points-30449',
    authDomain: 'project-points-30449.firebaseapp.com',
    storageBucket: 'project-points-30449.appspot.com',
    measurementId: 'G-X9KHJ3N77T',
  );

}